name: tmap_ui_sdk_example
description: Demonstrates how to use the tmap_ui_sdk plugin.

publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  tmap_ui_sdk:
    path: ../

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^8.0.1
  path_provider: ^2.0.14
  permission_handler: 10.2.0
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker/